### ISSUE TITLE
service_sysv_linux issue with for operator once using dash

### ISSUE THREAD

**Issue by EvgeniyPatlan** [kardianos/service#101]
Hi.
for operator in service_sysv_linux is incorrect for dash.
To get it worked correctly for all shells it should be changed from {1..10} to $(seq 1 10)

**Comment by EvgeniyPatlan** [comment]
Here is the pull request to fix it
https://github.com/kardianos/service/pull/102

**Comment by dbpercona** [comment]
Some history behind this problem,  starting with Debian Squeeze,  the default /bin/sh shell was changed from bash to dash.    Because of this,  any scripts that use the #!/bin/sh shebang that may run on Debian/Ubuntu, such as the kardianos init.d scripts, cannot use bash enhancements.   Brace expansion for sequences {x..y} was added to bash in version 3.0 and is not supported in dash.    The shellcheck static analysis tool can be used to catch these problems.
