### ISSUE TITLE
Cannot install service again after uninstall by sc command

### ISSUE THREAD

**Issue by delphikwok** [kardianos/service#125]
Hi Everyone,
I am new here. I found a problem that I installed my service by s.install() and delete the service by sc delete command and then I can not install again. Any idea?

Delphi

**Comment by kardianos** [comment]
What's the error message?

**Comment by delphikwok** [comment]
oh! I havn't notice the install() method has return an error. I will check.

**Comment by osleg** [comment]
This is most likely because of the eventlog handler. 
If you `sc delete` then the eventlog handler is not removed by the system and it will fail at this point https://github.com/kardianos/service/blob/master/service_windows.go#L219
I suggest to check for `existing` in error and if event log is already available just silently skip the error
