### ISSUE TITLE
linux environment variables os.Getenv() = nil

### ISSUE THREAD

**Issue by 4781121** [kardianos/service#24]
linux environment variables os.Getenv() = nil

**Comment by kardianos** [comment]
@4781121 Write more words, even in your own language please. I don't understand your issue.

Perhaps you are trying to do the following:
1. Device an environment variable in your personal .bashrc file.
2. Run a program as a service.
3. Try to access your environment variable in your program.

That won't work by definition. Services don't run in bash. They don't start in bash. .bashrc doesn't ever get used. That's why it's called a system service.

**Comment by 4781121** [comment]
Sorry! My English is not good.
是的, 就是你说的这个意思, 我无法在程序中获得系统中设置的环境变量, 但我又需要给服务中传入一些参数怎么做呢?

**Comment by kardianos** [comment]
To give the program a parameter I would recommend using either a
configuration file or or when installing the service, arrange for the
configuration "Arguments" parameter to store the parameters. Then the given
"Arguments" will be passed into the program each time it is ran.

So, for service install, set Config.Arguments. Then when running the
arguments (os.Args) will be passed in automatically to your program.

Close this issue if this makes sense to you.

via google translate:
为了给该计划的一个参数，我建议使用一个配置文件或者或安装服务时，安排配置“参数”参数存储的参数。然后给定的“论据”，将它跑了，每次被传递到程序中。

因此，对于服务的安装，设置Config.Arguments 。然后运行参数（ os.Args ）时，会自动传递到您的程序。

关闭这个问题，如果这对你有意义。

**Comment by 4781121** [comment]
thx
