### ISSUE TITLE
Windows service: unquoted service path can allow for privilege escalation

### ISSUE THREAD

**Issue by trespassing-potato** [kardianos/service#289]
Hello!

We use [Telegraf](https://github.com/influxdata/telegraf) (which depend on this library) and our vulnerability scanner notifies us of the following vulnerability with the telegraf service: [Windows Unquoted Search Path or Element can allow local privilege escalation
](https://www.rapid7.com/db/vulnerabilities/windows-unquoted-search-path-or-element/)

I did some brief digging around and I think the problem boils down to this line: https://github.com/kardianos/service/blob/36c9bf8c36a2a4ca4629fb338687a850bef3eee4/service_windows.go#L226

Here you take the path to the executing program (if I understood correctly) and later use it when you install the service. Doing this without adding quotes to the path means that the unquoted service path issue comes into effect.

You should be able to simply add quotes to the path, and in doing to solve the issue at hand.

**Comment by trespassing-potato** [comment]
see #290

**Comment by trespassing-potato** [comment]
Hello?

**Comment by masinger** [comment]
@trespassing-potato Could it be that you got fooled by your security scanner?

Because if you step into the m.CreateService(... call at line 256, you will see that the path is already being escaped by a call to syscall.EscapeArg() (see https://docs.microsoft.com/en-us/previous-versions/ms880421(v=msdn.10)?redirectedfrom=MSDN).

Note: I copied the comment from the pull request #290 - just in case someone stumbles upon this issue.

**Comment by trespassing-potato** [comment]
Yes, I believe so. I should have looked into it further before raising this issue, my apologies!

(I tried to reproduce the issue discovered by our scanner, but the installed service in question (telegraf) has a quoted path)

**Comment by rahulverma** [comment]
@trespassing-potato This vulnerability [CVE-2022-29583](https://nvd.nist.gov/vuln/detail/CVE-2022-29583) still shows up in scans. And its still not marked as invalid. Can you please help ?
