### ISSUE TITLE
FreeBSD 11: No service system detected

### ISSUE THREAD

**Issue by voltagex** [kardianos/service#98]
I've been asked to open this from https://github.com/bruhs/caddy-service/issues/7

I can help debug this if you can provide a binary that outputs more verbose information, as the caddy-service plugin doesn't give much info.

**Comment by kardianos** [comment]
@voltagex I would recommend you take a look at the examples and tests in this package. Once those are working on FreeBSD 11, then it should just work upstream.

**Comment by mike-pt** [comment]
@kardianos do you mean FreeBSD is actually supported?

I run into https://github.com/jedisct1/dnscrypt-proxy/issues/157 and I'm curious if they could in future add support for freebsd service install which would be great

**Comment by kardianos** [comment]
I don't run freebsd at this time. Send a PR.

**Comment by mike-pt** [comment]
I don't known GO, so unfortunately that won't happen.

I'm assuming its not supported at all (that's really only what I was trying to clarify) though since you're asking for a PR

**Comment by kardianos** [comment]
If you can describe the method that freebsd 11 would use to fulfill this package, that would help too.

**Comment by mike-pt** [comment]
In FreeBSD we would use a "rc.d" script, and those can then be start/stoped/restart using `service`... in more detail I think a spec of this would be:

## Service Install:
Create and rc.d script that uses "/usr/sbin/deamon" to start the dnscrypt-proxy bin, there's an example [here](https://redbyte.eu/en/blog/supervised-freebsd-init-script-for-go-deamon/) for a go program.
So I suppose this would need to create a template rc.d script and most of the same details passed as config to systemd/launched etc would be used?


## Service Enable/Disable
In older versions of FreeBSD you would need to manually add to "/etc/rc.conf" `someservice_name_enable=YES` (this is the same name you put in the rc.d script `rcvar.

In recent versions though (I think since 9 at least) you can use `sysrc` to set those (or check if they are set/what values etc)

## Service Start/Stop
Simple call `service name_of_service start` same for stop/restart 

## Service Uninstall
Delete the rc.d script and remove the rc.conf entry with `sysrc -x name_of_service`

**Comment by mike-pt** [comment]
I forgot to add system services are found in "/etc/rc.d" but user installed ones should go in "/usr/local/etc/rc.d" 

Likewise the binary should go in "/usr/local/bin" and the config in "/usr/local/etc/name_of_service", I suppose using `/usr/local/` as "$PREFIX" would help and that's what freebsd ports do I.E., and since that's a env var it can also be changed if the user prefers

**Comment by coanor** [comment]
> @voltagex I would recommend you take a look at the examples and tests in this package. Once those are working on FreeBSD 11, then it should just work upstream.

I'v tested under freebsd 11.2, its not working: `No service system detected`.

**Comment by kardianos** [comment]
I just tagged a new version that should include freebsd.
